import type { Metadata } from "next";
import { Inter} from 'next/font/google'
import "./globals.css";
import { ThemeProvider } from "next-themes";

const inter = Inter ({
  subsets: ['latin'],
  display: 'swap',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en" className={inter.className}>
      <body className="dark:bg-neutral-950 bg-neutral-100">
        <ThemeProvider defaultTheme="system" enableSystem attribute="class">
         {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
